language: java
jdk: openjdk11

branches:
  only:
  - master

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"

script: "./gradlew clean build"

before_deploy:
  - mkdir -p before-deploy # zip에 포함시킬 파일들을 담을 디렉토리 생성
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy * # before-deploy로 이동후 전체 압축
  - cd ../ && mkdir -p deploy # 상위 디렉토리로 이동후 deploy 디렉토리 생성
  - mv before-deploy/before-deploy.zip deploy/visionnote-back.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: visionnote
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait_until_deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: visionnote
    key: visionnote-back.zip
    bundle_type: zip
    application: visionnote-back-codedeploy
    deployment_group: visionnote-back-codedeploy-group
    region: ap-northeast-2
    wait_until_deployed: true

notifications:
  email:
    recipients:
    - esot3ria@gmail.com

env:
  global:
    secure: Xvk5Z8RhL5vX2piiCV4BzL7cRkt7o/TMlC85ol4kC2isFDGDK/+0fGjeBrlybCTGDESYKRg4Di5N9jGbs66lGWYkgbW8Efmjz8PkfZi6c3zD9guD68Nr/fM69TttUynT9oZnk73P+a15wQvWTM4i4TV3ZZvZeHpw/XwMg/UPIE48lm7FnCEzatwTJ6u9Oh3qk3DK8cuPFOEN0OXCsvJipnC/oG0swv/l1Au5EOKIeqwYDCKVzlnbudBscbTNCIbJsbfa+9s/Dnbt2KfPVGjBCL2FKifWidoiktJnPk+4Bi+3QjUs/84NOp4Gvi2quZ9XirzmKEm3uAhKmoHt2G/FearRmZn3UtLnVxemqSdgrH2Mdcl6GyVxsGfOrlwvIrwRmyC7q2932pQjBA9huIJlFKQSfP4Vc/gjnGKl7z9ALDRA/IFobiDMbEWHgxtaaNPBj5icBkE5n2KRuDvcCW/1Bbk0Fn1j9s/+4oTNevVp0uFEKybNtrxInLIJncl7z7xrLrB+Q9KLvTFMEzUz+FnYHYeFtAb5Woa7sAncCWAuV+BH3Xsq+Cphi0RG2d5vXVuOjTGizjFQfpcS4ZUeNQ2CqP8OVDIh5hPukKaMJLp3N9ruvWFetvU+0FbVBXMhfjsnt38XK3bfMNwGmPoq0MdOEq5LaFrbkST3+vPcTthtCLA=
