language: java
jdk: openjdk11

branches:
  only:
  - master

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"

script: "./gradlew clean build"

notifications:
  email:
    recipients:
    - esot3ria@gmail.com

env:
  global:
    secure: Xvk5Z8RhL5vX2piiCV4BzL7cRkt7o/TMlC85ol4kC2isFDGDK/+0fGjeBrlybCTGDESYKRg4Di5N9jGbs66lGWYkgbW8Efmjz8PkfZi6c3zD9guD68Nr/fM69TttUynT9oZnk73P+a15wQvWTM4i4TV3ZZvZeHpw/XwMg/UPIE48lm7FnCEzatwTJ6u9Oh3qk3DK8cuPFOEN0OXCsvJipnC/oG0swv/l1Au5EOKIeqwYDCKVzlnbudBscbTNCIbJsbfa+9s/Dnbt2KfPVGjBCL2FKifWidoiktJnPk+4Bi+3QjUs/84NOp4Gvi2quZ9XirzmKEm3uAhKmoHt2G/FearRmZn3UtLnVxemqSdgrH2Mdcl6GyVxsGfOrlwvIrwRmyC7q2932pQjBA9huIJlFKQSfP4Vc/gjnGKl7z9ALDRA/IFobiDMbEWHgxtaaNPBj5icBkE5n2KRuDvcCW/1Bbk0Fn1j9s/+4oTNevVp0uFEKybNtrxInLIJncl7z7xrLrB+Q9KLvTFMEzUz+FnYHYeFtAb5Woa7sAncCWAuV+BH3Xsq+Cphi0RG2d5vXVuOjTGizjFQfpcS4ZUeNQ2CqP8OVDIh5hPukKaMJLp3N9ruvWFetvU+0FbVBXMhfjsnt38XK3bfMNwGmPoq0MdOEq5LaFrbkST3+vPcTthtCLA=
