version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/s3/zip/visionnote-back/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 180
      runas: ubuntu
