server:
  port: 8080

spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: ENC(zITM5/nYwUxhXdNh0mEJulABglRAES5XIabttUBVihQgVXxT7iWhu8bFIYGWswNkbMCi5dscNwXzeHuD9qSHZ1WJCQaF39T9esLVcJmIqKBRornFBkgfs+zGdKWQQuSXZeYpl2k0us7dtWILZZsHLrZYhTYeK5bp/9nB74z9Vd8=)
    username: ENC(gvDA85V2d12rNTcPrr+W6h3ATK7NuHMURqxQWVTJmkpio94Ccduk9XYIzPZ+gcYP)
    password: ENC(VfYNpP98DxB3rZuke/EWyckynIX9+jP0wxd9ymw4LSv5LApiNR8/bmN2lnU5mNKt)

mybatis:
  type-aliases-package: org.swm.vnb.model
  mapper-locations: mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

jwt:
  header: Authorization
  secret: ENC(6G9N7wMf9N4E7WLnskaGQhGo+m2EROg9xOJEVARHZg/ZyQbxYkto8twrxQg+lv/2Y5xT1EpxoJwIH1D0T80Gj3gzN2q4AHH7fCtkCX3eEGG3kKiuekJ0tljGSHVYRW8X8ttobXrYv2JxXvcUb0z/KSsU4MmuDw/xAI57CbklY+zB+Z3K7WvjODynuZWAL/thARkJ1XnI4H1UiW3awKNjCicPm7jYihkS+ExSmTPjkNk=)
  token-validity-in-seconds: 86400

storage:
  s3:
    api-server-path: ENC(9rCSOhrX7I+tE0kDlffpO4Fvjpi+ru0EJBvywwUHFAiwohLE2Diqfiz6SeMspIPgkyg10sMlCB8JEiTk2K+I5A==)
    stt-server-path: ENC(9rCSOhrX7I+tE0kDlffpO4Fvjpi+ru0EJBvywwUHFAiwohLE2Diqfiz6SeMspIPgkyg10sMlCB8JEiTk2K+I5A==)

uri:
  stt-server: ENC(sBT9yH6em7npAkmojZ0xb7nRrKIR+NcsR9uFNAQYlxH7DeY1x3tY7tbTcRXk7JedbmCmie2iDge5zTbfNggj0g==)

logging:
  level:
    org.swm.vnb: DEBUG