server:
  port: 8080

spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: ENC(zITM5/nYwUxhXdNh0mEJulABglRAES5XIabttUBVihQgVXxT7iWhu8bFIYGWswNkbMCi5dscNwXzeHuD9qSHZ1WJCQaF39T9esLVcJmIqKBRornFBkgfs+zGdKWQQuSXZeYpl2k0us7dtWILZZsHLrZYhTYeK5bp/9nB74z9Vd8=)
    username: ENC(gvDA85V2d12rNTcPrr+W6h3ATK7NuHMURqxQWVTJmkpio94Ccduk9XYIzPZ+gcYP)
    password: ENC(VfYNpP98DxB3rZuke/EWyckynIX9+jP0wxd9ymw4LSv5LApiNR8/bmN2lnU5mNKt)

mybatis:
  type-aliases-package: org.swm.vnb.model
  mapper-locations: mapper/**/*.xml

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
